aiplay2/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib import auth
from django.contrib.auth.views import LoginView

from scene.views import HomeView, SceneDetailedSubmitView, SceneSolutionVisualizationView, ChallengeListView, \
    ChallengeAcceptView, ChallengeVisualizationView
from program.views import CodeListView, CodeDetailView, CodeCompileView

urlpatterns = [
    url(r'^$', HomeView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', LoginView.as_view()),
    url(r'^code/$', CodeListView.as_view()),
    url(r'^code/(?P<pk>\d+)/$', CodeDetailView.as_view(), name='code_detail'),
    url(r'^code/(?P<pk>\d+)/compile/$', CodeCompileView.as_view(), name='code_compile'),
    url(r'^scene/(?P<pk>\d+)/$', SceneDetailedSubmitView.as_view(), name='scene_detail'),
    url(r'^scene/(?P<pk>\d+)/solution/(?P<spk>\d+)/$', SceneSolutionVisualizationView.as_view(), name='scene_solution'),
    url(r'^challenge/$', ChallengeListView.as_view()),
    url(r'^challenge/(?P<pk>\d+)/accept/$', ChallengeAcceptView.as_view(), name='challenge_accept'),
    url(r'^challenge/(?P<pk>\d+)/$', ChallengeVisualizationView.as_view(), name='challenge_detail'),
]

scene/models.py
import markdown
from django.db import models

from judge.models import Solution, CombatSolution
from program.models import Code, RunningReport


class Scene(models.Model):
    TYPE_CHOICES = (
        ('game', 'Game'),
        ('combat', 'Combat')
    )

    title = models.CharField(max_length=192)
    statement = models.TextField(blank=True)
    time_limit = models.IntegerField(default=1000)
    judge = models.ForeignKey(Code, null=True, related_name="judge_set")
    html_analysis_code = models.ForeignKey(Code, null=True, related_name="analysis_set")
    scene_type = models.CharField(max_length=30, choices=TYPE_CHOICES)
    solutions = models.ManyToManyField(Solution, blank=True)

    def __str__(self):
        return self.get_scene_type_display() + ": " + self.title

    def get_statement_markdown(self):
        md = markdown.Markdown(
            extensions=['fenced_code',
                        'codehilite',
                        'tables',
                        ]
        )
        return md.convert(self.statement)


class Challenge(models.Model):
    code1 = models.ForeignKey(CombatSolution, related_name="code1_set")
    code2 = models.ForeignKey(CombatSolution, related_name="code2_set")
    create_time = models.DateTimeField(auto_now_add=True)
    accept_time = models.DateTimeField(blank=True, null=True)
    report0_judge = models.ForeignKey(RunningReport, blank=True, null=True, related_name="report0_judge_set")
    report1 = models.ForeignKey(RunningReport, blank=True, null=True, related_name="report1_set")
    report2 = models.ForeignKey(RunningReport, blank=True, null=True, related_name="report2_set")
    score1 = models.IntegerField(default=0)
    score2 = models.IntegerField(default=0)
    belong_to = models.ForeignKey(Scene)

templates/base.html
{% extends 'html_base.html' %}

{% block _content %}

  <div class="ui borderless main menu">
    <div class="ui container">
      <a href="/" class="header item">
        AI Coding Playground
      </a>
      <a href="/code/" class="item">Codes</a>
      <a href="/challenge/" class="item">Challenges</a>
      <a href="/login/" class="ui right item">
        {% if request.user.is_authenticated %}
          {{ request.user }}
        {% else %}
          Login
        {% endif %}
      </a>
    </div>
  </div>

  <div class="ui hidden divider"></div>

  <div class="ui container">
    <div style="height: 20px"></div>

  {% block content %}
    <h1 class="ui header">AI Coding Playground</h1>

    <div class="ui items">
    {% for scene in scene_list %}
      <div class="item">
        <div class="content">
          <a class="ui dividing header" href="{% url 'scene_detail' scene.pk %}">Scene #{{ scene.pk }}. {{ scene.title }}</a>
          <div class="description">{{ scene.get_statement_markdown | safe }}</div>
        </div>
      </div>
      <div class="ui hidden divider"></div>
    {% endfor %}
    </div>
  </div>
  {% endblock %}

  <div class="ui container" style="height: 100px"></div>

{% endblock %}

templates/html_base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>AI Coding Playground</title>
  <link href="{% static "node_modules/semantic-ui/dist/semantic.min.css" %}" rel="stylesheet">
  <link href="{% static "code.css" %}" rel="stylesheet">
  <script src="{% static "node_modules/jquery/dist/jquery.min.js" %}"></script>
  <script src="{% static "node_modules/semantic-ui/dist/semantic.min.js" %}"></script>
  <script src="{% static "node_modules/d3/dist/d3.min.js" %}"></script>
  <style>
    body {
      font-size: 16px;
    }
    .description, h1 {
      font-size: 20px;
    }
  </style>
  {% block style %}
  {% endblock %}
</head>
<body>
{% block _content %}
{% endblock %}

<script>
  $(".ui.dropdown").dropdown();
</script>
</body>
</html>