aiplay2/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib import auth
from django.contrib.auth.views import LoginView

from scene.views import HomeView, SceneDetailedSubmitView, SceneSolutionVisualizationView, ChallengeListView, \
    ChallengeAcceptView, ChallengeVisualizationView
from program.views import CodeListView, CodeDetailView, CodeCompileView

urlpatterns = [
    url(r'^$', HomeView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', LoginView.as_view()),
    url(r'^code/$', CodeListView.as_view()),
    url(r'^code/(?P<pk>\d+)/$', CodeDetailView.as_view(), name='code_detail'),
    url(r'^code/(?P<pk>\d+)/compile/$', CodeCompileView.as_view(), name='code_compile'),
    url(r'^scene/(?P<pk>\d+)/$', SceneDetailedSubmitView.as_view(), name='scene_detail'),
    url(r'^scene/(?P<pk>\d+)/solution/(?P<spk>\d+)/$', SceneSolutionVisualizationView.as_view(), name='scene_solution'),
    url(r'^challenge/$', ChallengeListView.as_view()),
    url(r'^challenge/(?P<pk>\d+)/accept/$', ChallengeAcceptView.as_view(), name='challenge_accept'),
    url(r'^challenge/(?P<pk>\d+)/$', ChallengeVisualizationView.as_view(), name='challenge_detail'),
]

program/models.py
from django.db import models
from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter

from sandbox.lang import SUPPORTED_LANG
import traceback


def transform_code_to_html(code, lang):
    return highlight(code, get_lexer_by_name(lang), HtmlFormatter())


class Code(models.Model):

    code = models.TextField()
    language = models.CharField(choices=SUPPORTED_LANG, max_length=12)
    workspace = models.CharField(max_length=192, blank=True)
    is_compiled = models.IntegerField(choices=(
        (0, 'Unknown'),
        (1, 'Success'),
        (2, 'Failed'),
    ), default=0)
    compiler_message = models.TextField(blank=True)

    def __str__(self):
        return str(self.pk) + ": " + self.code[:30] + "..."

    def code_html(self):
        return transform_code_to_html(self.code, self.language)


class RunningReport(models.Model):
    code = models.ForeignKey(Code)
    raw_output = models.TextField(blank=True)
    time_consumption = models.FloatField(default=0)
    return_code = models.IntegerField(default=0)
    finish_time = models.DateTimeField(blank=True, null=True)  # if this is null, this is not finished

scene/models.py
import markdown
from django.db import models

from judge.models import Solution, CombatSolution
from program.models import Code, RunningReport


class Scene(models.Model):
    TYPE_CHOICES = (
        ('game', 'Game'),
        ('combat', 'Combat')
    )

    title = models.CharField(max_length=192)
    statement = models.TextField(blank=True)
    time_limit = models.IntegerField(default=1000)
    judge = models.ForeignKey(Code, null=True, related_name="judge_set")
    html_analysis_code = models.ForeignKey(Code, null=True, related_name="analysis_set")
    scene_type = models.CharField(max_length=30, choices=TYPE_CHOICES)
    solutions = models.ManyToManyField(Solution, blank=True)

    def __str__(self):
        return self.get_scene_type_display() + ": " + self.title

    def get_statement_markdown(self):
        md = markdown.Markdown(
            extensions=['fenced_code',
                        'codehilite',
                        'tables',
                        ]
        )
        return md.convert(self.statement)


class Challenge(models.Model):
    code1 = models.ForeignKey(CombatSolution, related_name="code1_set")
    code2 = models.ForeignKey(CombatSolution, related_name="code2_set")
    create_time = models.DateTimeField(auto_now_add=True)
    accept_time = models.DateTimeField(blank=True, null=True)
    report0_judge = models.ForeignKey(RunningReport, blank=True, null=True, related_name="report0_judge_set")
    report1 = models.ForeignKey(RunningReport, blank=True, null=True, related_name="report1_set")
    report2 = models.ForeignKey(RunningReport, blank=True, null=True, related_name="report2_set")
    score1 = models.IntegerField(default=0)
    score2 = models.IntegerField(default=0)
    belong_to = models.ForeignKey(Scene)

scene/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import TemplateView

from judge.models import CombatSolution, GameSolution
from judge.views import JudgeModule, create_solution
from scene.models import Scene, Challenge


class ChallengeJudgeModule(JudgeModule):

    @staticmethod
    def solve_rating(winner: CombatSolution, loser: CombatSolution, tie=False):
        def get_k(x):
            if x.rating < 2100:
                return 32
            elif x.rating < 2400:
                return 24
            else: return 16

        if winner.rating == 0:
            winner.rating = 1500
        if loser.rating == 0:
            loser.rating = 1500
        pa = 1 / (1 + pow(10, (loser.rating - winner.rating)) / 400)
        pb = 1 / (1 + pow(10, (winner.rating - loser.rating)) / 400)
        sa, sb = 1, 0
        if tie: sa, sb = 0.5, 0.5
        winner.rating += get_k(winner) * (sa - pa)
        loser.rating += get_k(loser) * (sb - pb)
        winner.save(update_fields=['rating'])
        loser.save(update_fields=['rating'])

    @staticmethod
    def judge_challenge(challenge, solution_a: CombatSolution, solution_b: CombatSolution, judge, time_limit):
        a, b, j = JudgeModule.judge_combat(solution_a, solution_b, judge, time_limit)
        challenge.report0_judge = j
        challenge.report1 = a
        challenge.report2 = b
        x, y = JudgeModule.fetch_score(j)
        challenge.score1, challenge.score2 = x, y
        challenge.save()
        if x >= y:
            ChallengeJudgeModule.solve_rating(solution_a, solution_b, tie=x == y)
        else:
            ChallengeJudgeModule.solve_rating(solution_b, solution_a)


class HomeView(ListView):
    template_name = 'base.html'
    queryset = Scene.objects.all()
    context_object_name = 'scene_list'


class SceneDetailedSubmitView(DetailView):
    queryset = Scene.objects.all()
    context_object_name = 'scene'
    template_name = 'scene/scene_base.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        ls = list(map(lambda x: x.pk, data['scene'].solutions.all()))
        if data['scene'].scene_type == 'game':
            data["solutions"] = GameSolution.objects.filter(pk__in=ls)
        else:
            data['solutions'] = CombatSolution.objects.filter(pk__in=ls)
        return data

    def post(self, request, pk):
        scene = get_object_or_404(Scene, pk=pk)
        solution = create_solution(request.POST['code'], request.POST["lang"], request.user, scene.scene_type)
        scene.solutions.add(solution)
        if scene.scene_type == 'game':
            JudgeModule.judge_game(solution, scene.judge, scene.time_limit / 1000)
        return redirect(request.path)


class SceneSolutionVisualizationView(TemplateView):
    template_name = 'scene/visualization.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['scene'] = get_object_or_404(Scene, pk=self.kwargs['pk'])
        data['solution'] = get_object_or_404(GameSolution, pk=self.kwargs['spk'])
        return data


class ChallengeListView(ListView):
    template_name = 'challenge/challenge_list.html'
    queryset = Challenge.objects.all()
    context_object_name = 'challenge_list'


class ChallengeVisualizationView(TemplateView):
    template_name = 'challenge/visualization.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['challenge'] = get_object_or_404(Challenge, pk=self.kwargs['pk'])
        data['scene'] = data['challenge'].belong_to
        return data


class ChallengeAcceptView(View):
    # again: get for demo purpose
    def get(self, request, pk):
        challenge = get_object_or_404(Challenge, pk=pk)
        ChallengeJudgeModule.judge_challenge(challenge, challenge.code1, challenge.code2, challenge.belong_to.judge,
                                             challenge.belong_to.time_limit / 1000)
        return redirect("/challenge/")

templates/scene/scene_base.html
{% extends 'base.html' %}

{% block content %}

  <h1 class="ui header">Scene #{{ scene.pk }}: {{ scene.title }}</h1>

  {{ scene.get_statement_markdown | safe }}

  <h2 class="ui header">Submit your code</h2>

  <form class="ui form" method="post">
    {% csrf_token %}
    <div class="field">
      <label>Language:</label>
      <div class="ui selection search submit language dropdown">
        <input name="lang" id="id_lang" type="hidden" value="cpp">
        <i class="dropdown icon"></i>
        <div class="text"></div>
        <div class="menu">
          <div class="item" data-value="cpp">C++</div>
          <div class="item" data-value="py">Python</div>
          <div class="item" data-value="java">Java</div>
        </div>
      </div>
    </div>
    <div class="field">
      <label>Code:</label>
      <textarea name="code" style="font-family: monospace"></textarea>
    </div>
    <div class="field">
      <button class="ui button positive">Submit</button>
    </div>
  </form>

  <h2 class="ui header">Available Solutions</h2>

  <table class="ui stripped celled table">
  {% if scene.scene_type == "game" %}
    <thead>
      <tr>
        <th>#</th>
        <th>Author</th>
        <th>Created</th>
        <th>Language</th>
        <th>Score</th>
        <th>Process</th>
      </tr>
    </thead>
    <tbody>
    {% for solution in solutions %}
      <tr>
        <td>{{ solution.pk }}</td>
        <td>{{ solution.author }}</td>
        <td>{{ solution.create_time }}</td>
        <td><a href="{% url 'code_detail' solution.code.pk %}">{{ solution.code.get_language_display }}</a></td>
        <td>{{ solution.score }}</td>
        <td><a href="{% url 'scene_solution' scene.pk solution.pk %}">Visualization</a></td>
      </tr>
    {% endfor %}
    </tbody>
  {% else %}
    <thead>
      <tr>
        <th>#</th>
        <th>Author</th>
        <th>Created</th>
        <th>Language</th>
        <th>Rating</th>
      </tr>
    </thead>
    <tbody>
    {% for solution in solutions %}
      <tr>
        <td>{{ solution.pk }}</td>
        <td>{{ solution.author }}</td>
        <td>{{ solution.create_time }}</td>
        <td><a href="{% url 'code_detail' solution.code.pk %}">{{ solution.code.get_language_display }}</a></td>
        <td>{{ solution.rating }}</td>
      </tr>
    {% endfor %}
    </tbody>
  {% endif %}
  </table>

{% endblock %}

templates/scene/visualization.html
{% extends 'base.html' %}

{% block content %}

  <h1 class="ui header">Scene {{ scene.title }}: Solution {{ solution.pk }}</h1>

  <div class="ui grid">
    <div class="nine wide column">
      <div id="main">

      </div>
    </div>
    <div class="seven wide column">
      <table class="ui definition celled table">
        <thead>
          <tr>
            <th></th>
            <th>Judge</th>
            <th>User</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Code</td>
            <td><a href="{% url 'code_detail' solution.judge_report.code_id %}">#{{ solution.judge_report.code_id }}</a></td>
            <td><a href="{% url 'code_detail' solution.user_report.code_id %}">#{{ solution.user_report.code_id }}</a></td>
          </tr>
          <tr>
            <td>CPU Time</td>
            <td>{{ solution.judge_report.time_consumption | floatformat:3 }}</td>
            <td>{{ solution.user_report.time_consumption | floatformat:3 }}</td>
          </tr>
          <tr>
            <td>Exit Code</td>
            <td>{{ solution.judge_report.return_code }}</td>
            <td>{{ solution.user_report.return_code }}</td>
          </tr>
        </tbody>
      </table>
      <div class="ui form">
        <div class="field">
          <textarea style="font-family:monospace" rows="40" id="output">{{ solution.judge_report.raw_output }}</textarea>
        </div>
      </div>
    </div>
  </div>

  <script>
    {{ scene.html_analysis_code.code | safe }}
  </script>

{% endblock %}